version: "3.8"

services:
  database:
    build: ./database

    ports:
      - 3307:3306

    environment:
      MYSQL_DATABASE: project_vacations
      MYSQL_ROOT_PASSWORD: "!11A7a3@dg"
      ACCEPT_EULA: "Y"

    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci", "--default-authentication-plugin=mysql_native_password"]

    restart: unless-stopped

    volumes:
      - project_vacations:/var/lib/mysql

  #---------------------------------------------------------------

  backend:
    build: ./backend

    ports:
      - 4000:4000

    restart: unless-stopped

    volumes:
      - ./Backend:/app

    depends_on:
      - database
  #---------------------------------------------------------------

  frontend:
    build: ./frontend

    ports:
      - 3000:3000

    restart: unless-stopped

    volumes:
      - ./frontend:/app

    depends_on:
      - backend

#---------------------------------------------------------------

volumes:
  project_vacations:

  #docker-compose up -d --build
